name: frp-controller

services:
  cache:
    image: valkey/valkey:8-alpine
    restart: unless-stopped
    volumes:
      - cache:/data
    # ports:
    #   - "6379:6379"

  app:
    build: .
    image: ghcr.io/cnily03/ret2shell-frp-controller:latest
    restart: unless-stopped
    depends_on:
      - cache
    ports:
      - "3000:3000"
    volumes:
      - ./config.toml:/app/config.toml:ro

volumes:
  cache:
